"""update column with foreignkey

Revision ID: 0b7fa4b4ac38
Revises: e16234c0e5fb
Create Date: 2025-07-01 11:41:06.731033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7fa4b4ac38'
down_revision: Union[str, Sequence[str], None] = 'e16234c0e5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flows', sa.Column('group', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('flows_parent_fkey'), 'flows', type_='foreignkey')
    op.create_foreign_key(None, 'flows', 'groups', ['group'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('flows', 'parent')
    op.add_column('groups', sa.Column('period', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('groups_parent_fkey'), 'groups', type_='foreignkey')
    op.create_foreign_key(None, 'groups', 'periods', ['period'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('groups', 'parent')
    op.alter_column('judges', 'competition',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('periods', sa.Column('competition', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('periods_parent_fkey'), 'periods', type_='foreignkey')
    op.create_foreign_key(None, 'periods', 'competitions', ['competition'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('periods', 'parent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('parent', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'periods', type_='foreignkey')
    op.create_foreign_key(op.f('periods_parent_fkey'), 'periods', 'competitions', ['parent'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('periods', 'competition')
    op.alter_column('judges', 'competition',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('groups', sa.Column('parent', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.create_foreign_key(op.f('groups_parent_fkey'), 'groups', 'periods', ['parent'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('groups', 'period')
    op.add_column('flows', sa.Column('parent', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flows', type_='foreignkey')
    op.create_foreign_key(op.f('flows_parent_fkey'), 'flows', 'groups', ['parent'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('flows', 'group')
    # ### end Alembic commands ###
