"""add created_at and updated_at to Period

Revision ID: 141314e54206
Revises: 5393fce94550
Create Date: 2025-07-01 13:41:41.938703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141314e54206'
down_revision: Union[str, Sequence[str], None] = '5393fce94550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('periods', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periods', 'updated_at')
    op.drop_column('periods', 'created_at')
    # ### end Alembic commands ###
