"""add created_at updated_at for Group

Revision ID: 20d1f84d8fbf
Revises: 342e3737af97
Create Date: 2025-07-02 14:36:34.244272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d1f84d8fbf'
down_revision: Union[str, Sequence[str], None] = '342e3737af97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('groups', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'updated_at')
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
