"""del fullkey from Period

Revision ID: 5393fce94550
Revises: efa272a183cb
Create Date: 2025-07-01 13:38:40.536111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5393fce94550'
down_revision: Union[str, Sequence[str], None] = 'efa272a183cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('periods', 'fullkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('fullkey', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
