"""add created_at updated_at for Flows

Revision ID: 59b7f4f7a4a7
Revises: 20d1f84d8fbf
Create Date: 2025-07-02 15:00:14.606382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b7f4f7a4a7'
down_revision: Union[str, Sequence[str], None] = '20d1f84d8fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flows', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('flows', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flows', 'updated_at')
    op.drop_column('flows', 'created_at')
    # ### end Alembic commands ###
