"""add started_at and completed_at in Competition

Revision ID: 6543d4f4ac6f
Revises: 010f78e389a0
Create Date: 2025-06-30 10:50:47.164383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6543d4f4ac6f'
down_revision: Union[str, Sequence[str], None] = '010f78e389a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('competitions', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'completed_at')
    op.drop_column('competitions', 'started_at')
    # ### end Alembic commands ###
