"""del key from athletes

Revision ID: 7bfc16c3cef6
Revises: cee255940512
Create Date: 2025-07-01 11:54:19.687053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bfc16c3cef6'
down_revision: Union[str, Sequence[str], None] = 'cee255940512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('athletes_key_key'), 'athletes', type_='unique')
    op.drop_column('athletes', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athletes', sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('athletes_key_key'), 'athletes', ['key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
