"""refactoring models

Revision ID: ae97d60c81c0
Revises: 088ab7708ce7
Create Date: 2025-06-30 12:23:40.215987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae97d60c81c0'
down_revision: Union[str, Sequence[str], None] = '088ab7708ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.alter_column('competitions', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'ACTIVE', 'COMPLETED', name='competitionstatus'),
               nullable=False)
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('competitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('competitions', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('fullname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('competitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('competitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('competitions', 'status',
               existing_type=postgresql.ENUM('PLANNED', 'ACTIVE', 'COMPLETED', name='competitionstatus'),
               nullable=True)
    op.drop_column('competitions', 'full_name')
    # ### end Alembic commands ###
