"""add judjes

Revision ID: e16234c0e5fb
Revises: ca5645aac550
Create Date: 2025-07-01 11:36:33.066161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16234c0e5fb'
down_revision: Union[str, Sequence[str], None] = 'ca5645aac550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('competition', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('grade', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('sign', sa.Boolean(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('pos', sa.SmallInteger(), nullable=False),
    sa.Column('rank', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['competition'], ['competitions.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('judges')
    # ### end Alembic commands ###
