"""update period model

Revision ID: efa272a183cb
Revises: 7bfc16c3cef6
Create Date: 2025-07-01 13:37:25.286087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efa272a183cb'
down_revision: Union[str, Sequence[str], None] = '7bfc16c3cef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('periods', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('periods', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('periods', 'min_to')
    op.drop_column('periods', 'min_from')
    op.drop_column('periods', 'value')
    op.drop_column('periods', 'hour_to')
    op.drop_column('periods', 'hour_from')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('periods', sa.Column('hour_from', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('periods', sa.Column('hour_to', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('periods', sa.Column('value', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('periods', sa.Column('min_from', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('periods', sa.Column('min_to', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('periods', 'completed_at')
    op.drop_column('periods', 'started_at')
    op.drop_column('periods', 'date')
    # ### end Alembic commands ###
